name: Backend CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Sets up a Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Installs dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cbdc-backend/requirements.txt
      
      # Placeholder for running tests
      - name: Run tests (placeholder)
        run: |
          echo "No tests configured yet. Add your test command here!"
          
      # Optional: A step to build the Docker image to ensure the Dockerfile is valid
      - name: Build Docker image
        run: |
          docker build --file cbdc-backend/Dockerfile --tag my-image-name:$(date +%s) . 